### PR TITLE
Restructures GCP/AAD IDP config docs

### PR DESCRIPTION
**Pull request by tfelix**
Removes duplicate documentation and unifies it.
Added proper Dhall snippets from meshfed.

### CODE REVIEW

**Comment by meshcloud-gmbh** [comment]
Task linked: [CU-8my9cr Identity Lookup Azure config docs incomplete](https://app.clickup.com/t/8my9cr)

**Comment by SimonTheLeg** [comment]
I am a bit confused: How does this PR differ from #278?

**Comment by tfelix** [comment]
I am now confused as well... :D

**Comment by tfelix** [comment]
Seems I was sleeping and this PR is already merged. Branch was gone on remote that gave me the wrong hints.

**Pull request closed without merging**
