### PR TITLE
doc(identityconnector): improve documentation for identityconnector

### PR DESCRIPTION
**Pull request by JohannesRudolph**

### CODE REVIEW

**Review by felixzieger — CHANGES_REQUESTED** [review]
I recently discussed with @henryde that the model will

**Comment by meshcloud-gmbh** [comment]
Task linked: [CU-8jxxmt LDAP Identity Connector Configuration model is unclear](https://app.clickup.com/t/8jxxmt)

**Comment by SimonTheLeg** [comment]
@pubudug with the merging of #280. Does this PR become obsolete and can be closed?

**Comment by pubudug** [comment]
> @pubudug with the merging of #280. Does this PR become obsolete and can be closed?

I would say so. There were a lot of changes to the dhall config that most of the information in this PR would be outdated. The new version can be seen at https://docs.meshcloud.io/docs/meshstack.customer-group-sync.html

**Comment by JohannesRudolph** [comment]
As discussed with @pubudug closing this PR as out of date

**Pull request closed without merging**
